name: build-plugin

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

env:
  NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Write NuGet.Config
        run: |
          cat <<EOF > NuGet.Config
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <add key="github" value="https://nuget.pkg.github.com/jellyfin/index.json" />
              <add key="nuget" value="https://api.nuget.org/v3/index.json" />
            </packageSources>
          </configuration>
          EOF

      - name: Publish & pack
        run: |
          dotnet publish AniLibriaStrmPlugin.csproj -c Release -o publish
          cd publish
          zip -r ../AniLibriaStrm_${{ github.ref_name }}.zip .
          cd ..
          sha256sum AniLibriaStrm_${{ github.ref_name }}.zip > checksum.txt

      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: AniLibria STRM ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          files: |
            AniLibriaStrm_${{ github.ref_name }}.zip
            checksum.txt
