name: build-plugin

on:
  push:
    tags: ['*']
  workflow_dispatch:

permissions:
  contents: write
  packages: read

env:
  JELLYFIN_NUGET_PAT: ${{ secrets.JELLYFIN_NUGET_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # ────────────────────────────────────────────────
    - name: Checkout
      uses: actions/checkout@v4

    # .NET + авторизация к feed'у Jellyfin
    - name: Setup .NET + GitHub Packages auth
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        source-url: https://nuget.pkg.github.com/jellyfin/index.json
        owner: jellyfin                         # важно: владелец feed'а
      env:
        NUGET_AUTH_TOKEN: ${{ env.JELLYFIN_NUGET_PAT }}

    # ────────────────────────────────────────────────
    # Сборка плагина (+ meta.json) через JPRM
    - name: Build Jellyfin plugin  ➜  zip + meta.json
      uses: oddstr13/jellyfin-plugin-repository-manager@v1.1.1
      id: jprm
      with:
        dotnet-target: net9.0                     # TFM вашего плагина
        # Берём версию из тега (без префикса «v»)
        version: ${{ github.ref_name }}

    # ────────────────────────────────────────────────
    # Контрольные суммы (по желанию)
    - name: Generate checksums
      run: |
        md5sum    "${{ steps.jprm.outputs.artifact }}" > "${{ steps.jprm.outputs.artifact }}.md5"
        sha256sum "${{ steps.jprm.outputs.artifact }}" > "${{ steps.jprm.outputs.artifact }}.sha256"

    # ────────────────────────────────────────────────
    # Релиз
    - name: Release on GitHub
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: AniLibria STRM ${{ github.ref_name }}
        generate_release_notes: true
        files: |
          ${{ steps.jprm.outputs.artifact }}
          ${{ steps.jprm.outputs.artifact }}.md5
          ${{ steps.jprm.outputs.artifact }}.sha256
